jdk: oraclejdk8
language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
before_install:
- git clone https://github.com/Trumeet/Maven.git ./repo
- "./gradlew exportVersion"
- export VERSION=$(cat version.txt)
script:
- "./gradlew :library:uploadArchives :navigationbar:uploadArchives"
before_deploy:
- |
  if ! [ "$BEFORE_DEPLOY_RUN" ]; then
    export BEFORE_DEPLOY_RUN=1;
    chmod +x ./deploy_repo.sh
    git tag $VERSION
  fi
deploy:
  - provider: script
    script: ./deploy_repo.sh
    on:
      repo: Trumeet/Setupwizard